[project]
name = "ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "importlib-resources>=7.1.0",
    "jupyterlab>=4.6.3",
    "jupyterlab-lsp>=5.3.0",
    "matplotlib>=3.11.1",
    "pillow>=12.3.0",
    "tensorflow[and-cuda]>=2.21.0",
    "tensorflow-datasets>=4.9.10",
    "tensorflow-hub>=0.16.1",
    "tf-models-official>=2.1.0.dev2",
    "ipykernel>=7.3.0",
]

[tool.pyright]
typeCheckingMode = "basic"
reportAttributeAccessIssue = false
